/**
 * Marketing-local demo data for Landing V2 Hero Modern dashboard.
 * No DB. Distinct from production user data.
 */

export const HERO_MODERN_DEMO = {
  greeting: 'Dzień dobry,',
  userName: 'Marta',
  nearest: {
    typeLabel: 'Ślub',
    coupleName: 'Julia i Maksymilian',
    dateKey: '2027-06-12',
    day: '12',
    month: 'cze',
    weekday: 'sobota',
    longDate: '12 czerwca 2027',
    time: '15:00',
    location: 'Hotel Stary, Kraków',
    countdown: {
      value: '28',
      unit: 'dni',
      caption: 'do ślubu',
      mobileRelative: 'za 28 dni',
    },
  },
  upcoming: [
    {
      id: 'u1',
      typeLabel: 'Ślub',
      coupleName: 'Ola i Bartek',
      day: '3',
      month: 'lip',
      time: '15:00',
      location: 'Dwór Sanna, Lublin',
      relative: 'za 49 dni',
    },
    {
      id: 'u2',
      typeLabel: 'Sesja',
      coupleName: 'Natalia i Kacper',
      day: '17',
      month: 'lip',
      time: '17:00',
      location: 'Park Cytadela, Poznań',
      relative: 'za 63 dni',
    },
    {
      id: 'u3',
      typeLabel: 'Ślub',
      coupleName: 'Zofia i Marek',
      day: '7',
      month: 'sie',
      time: '14:30',
      location: 'Pałac Mała Wieś',
      relative: 'za 84 dni',
    },
  ],
  tasks: [
    {
      id: 't1',
      title: 'Sprawdź brief przed wyjazdem',
      meta: 'Julia i Maksymilian',
      due: '12 cze',
    },
    {
      id: 't2',
      title: 'Potwierdź godzinę ceremonii',
      meta: 'Julia i Maksymilian',
      due: '12 cze',
    },
    {
      id: 't3',
      title: 'Wyślij przypomnienie o ankiecie',
      meta: 'Ola i Bartek',
      due: '20 cze',
    },
  ],
  notifications: [
    {
      id: 'n1',
      type: 'info' as const,
      title: 'Ankieta przedślubna zaktualizowana',
      message: 'Julia i Maksymilian uzupełnili odpowiedzi do przeglądu.',
      date: '28 kwi',
      unread: true,
    },
    {
      id: 'n2',
      type: 'success' as const,
      title: 'Dane do umowy wysłane',
      message: 'Para otrzymała bezpieczny link do uzupełnienia danych.',
      date: '2 maj',
      unread: true,
    },
    {
      id: 'n3',
      type: 'info' as const,
      title: 'Nowe zlecenie z ankiety',
      message: 'Ola i Bartek — nowe zgłoszenie czeka na przegląd.',
      date: '5 maj',
      unread: false,
    },
    {
      id: 'n4',
      type: 'warning' as const,
      title: 'Nowe dane do umowy',
      message: 'Zofia i Marek przesłali poprawione dane kontraktowe.',
      date: '8 maj',
      unread: false,
    },
  ],
  deadlines: [
    {
      id: 'd1',
      title: 'Marta i Jakub',
      day: '18',
      month: 'maj',
      dueLabel: '18 maja 2026',
      contextLabel: 'za 12 dni',
      nearest: true,
    },
    {
      id: 'd2',
      title: 'Anna i Piotr',
      day: '2',
      month: 'cze',
      dueLabel: '2 czerwca 2026',
      contextLabel: 'za 27 dni',
      nearest: false,
    },
    {
      id: 'd3',
      title: 'Kasia i Tomek',
      day: '14',
      month: 'cze',
      dueLabel: '14 czerwca 2026',
      contextLabel: 'za 39 dni',
      nearest: false,
    },
  ],
  /** Matches production Modern sidebar primary labels (marketing subset). */
  nav: [
    { id: 'dashboard', label: 'Pulpit', active: true },
    { id: 'notifications', label: 'Powiadomienia', active: false },
    { id: 'finances', label: 'Finanse', active: false },
    { id: 'weddings', label: 'Śluby', active: false },
    { id: 'sessions', label: 'Sesje', active: false },
    { id: 'calendar', label: 'Kalendarz', active: false },
    { id: 'tasks', label: 'Zadania', active: false },
    { id: 'pending', label: 'Oczekujące', active: false },
    { id: 'questionnaires', label: 'Ankiety', active: false },
  ],
} as const
