import type { SystemVariableDef } from '@/lib/variables/registry/types'

/** Company Details — never asked in couple questionnaires. */
export const COMPANY_VARIABLES: SystemVariableDef[] = [
  {
    id: 'company_name',
    label: 'Nazwa firmy',
    description:
      'Pobierane z Dane firmy. Używane w umowach i dokumentach.',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.name',
    aliases: ['studio_name'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 610,
  },
  {
    id: 'company_owner',
    label: 'Właściciel',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.owner',
    aliases: ['owner'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 612,
  },
  {
    id: 'company_representative',
    label: 'Imię i nazwisko reprezentanta',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.photographerName',
    aliases: ['photographer_name'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 615,
  },
  {
    id: 'company_address',
    label: 'Adres firmy',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.address',
    aliases: ['studio_address'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 620,
  },
  {
    id: 'company_nip',
    label: 'NIP',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.nip',
    aliases: ['company_tax_id'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 630,
  },
  {
    id: 'company_vat',
    label: 'VAT ID',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.vat',
    aliases: ['vat'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 635,
  },
  {
    id: 'company_regon',
    label: 'REGON',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.regon',
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 640,
  },
  {
    id: 'company_bank_account',
    label: 'Numer konta',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.bankAccount',
    aliases: ['bank_account'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 650,
  },
  {
    id: 'company_iban',
    label: 'IBAN',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.iban',
    aliases: ['iban'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 652,
  },
  {
    id: 'company_swift',
    label: 'SWIFT',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.swift',
    aliases: ['swift'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 654,
  },
  {
    id: 'company_email',
    label: 'E-mail firmy',
    category: 'company',
    source: 'company',
    type: 'email',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.email',
    aliases: ['studio_email'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 660,
  },
  {
    id: 'company_phone',
    label: 'Telefon firmy',
    category: 'company',
    source: 'company',
    type: 'phone',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.phone',
    aliases: ['studio_phone'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 670,
  },
  {
    id: 'company_website',
    label: 'Strona WWW',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.website',
    aliases: ['studio_website'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 680,
  },
  {
    id: 'company_instagram',
    label: 'Instagram',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.instagram',
    aliases: ['instagram'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 682,
  },
  {
    id: 'company_facebook',
    label: 'Facebook',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.facebook',
    aliases: ['facebook'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 684,
  },
  {
    id: 'company_logo',
    label: 'Logo',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.logo',
    aliases: ['studio_logo'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 690,
  },
  {
    id: 'company_signature',
    label: 'Podpis',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.signature',
    aliases: ['studio_signature', 'signature'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 695,
  },
  {
    id: 'company_stamp',
    label: 'Pieczęć',
    category: 'company',
    source: 'company',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'company',
    legacyKey: 'studio.stamp',
    aliases: ['stamp'],
    documentSection: 'studio',
    documentDataSource: 'studio',
    sortOrder: 698,
  },
]
