import type { SystemVariableDef } from '@/lib/variables/registry/types'

/** Couple / bride / groom — questionnaire + CRM facing. */
export const COUPLE_VARIABLES: SystemVariableDef[] = [
  {
    id: 'bride_first_name',
    label: 'Imię Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.firstName',
    questionType: 'text',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 10,
  },
  {
    id: 'bride_last_name',
    label: 'Nazwisko Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.lastName',
    questionType: 'text',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 20,
  },
  {
    id: 'bride_phone',
    label: 'Telefon Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'phone',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.phone',
    questionType: 'phone',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 30,
  },
  {
    id: 'bride_email',
    label: 'E-mail Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'email',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.email',
    questionType: 'email',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 40,
  },
  {
    id: 'bride_address',
    label: 'Adres Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.address',
    questionType: 'textarea',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 50,
  },
  {
    id: 'bride_pesel',
    label: 'PESEL Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.pesel',
    aliases: ['pesel'],
    questionType: 'text',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 55,
  },
  {
    id: 'groom_first_name',
    label: 'Imię Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.firstName',
    questionType: 'text',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 110,
  },
  {
    id: 'groom_last_name',
    label: 'Nazwisko Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.lastName',
    questionType: 'text',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 120,
  },
  {
    id: 'groom_phone',
    label: 'Telefon Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'phone',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.phone',
    questionType: 'phone',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 130,
  },
  {
    id: 'groom_email',
    label: 'E-mail Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'email',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.email',
    questionType: 'email',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 140,
  },
  {
    id: 'groom_address',
    label: 'Adres Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.address',
    questionType: 'textarea',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 150,
  },
  {
    id: 'groom_pesel',
    label: 'PESEL Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.pesel',
    questionType: 'text',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 155,
  },
  {
    id: 'partner1_full_name',
    label: 'Partner 1 — imię i nazwisko',
    labelEn: 'Partner 1 full name',
    description:
      'Neutral full name for couple.partner1 (UI may label this slot as bride).',
    category: 'couple',
    source: 'computed',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'computed',
    legacyKey: 'couple.partner1',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 1,
  },
  {
    id: 'partner2_full_name',
    label: 'Partner 2 — imię i nazwisko',
    labelEn: 'Partner 2 full name',
    description:
      'Neutral full name for couple.partner2 (UI may label this slot as groom).',
    category: 'couple',
    source: 'computed',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'computed',
    legacyKey: 'couple.partner2',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 2,
  },
  {
    id: 'couple_full_names',
    label: 'Para młoda — pełne imiona',
    labelEn: 'Couple full names',
    description:
      'Composite of partner1 and partner2 full names joined by the template separator (default " i ").',
    category: 'couple',
    source: 'computed',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'computed',
    aliases: ['couple.full_names', 'couple_names'],
    documentSection: 'additional',
    documentDataSource: 'computed',
    sortOrder: 3,
  },
  {
    id: 'bride_full_name',
    label: 'Panna młoda — imię i nazwisko',
    labelEn: 'Bride full name',
    description:
      'Legacy role label for partner1_full_name when the wedding UI assigns partner1 as bride.',
    category: 'couple',
    source: 'computed',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'computed',
    legacyKey: 'bride.name',
    aliases: ['bride.name'],
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 5,
  },
  {
    id: 'groom_full_name',
    label: 'Pan młody — imię i nazwisko',
    labelEn: 'Groom full name',
    description:
      'Legacy role label for partner2_full_name when the wedding UI assigns partner2 as groom.',
    category: 'couple',
    source: 'computed',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'computed',
    legacyKey: 'groom.name',
    aliases: ['groom.name'],
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 6,
  },
  {
    id: 'marketing_consent',
    label: 'Zgoda marketingowa',
    labelEn: 'Marketing consent',
    description: 'Zgoda na wykorzystanie materiałów do celów marketingowych.',
    category: 'couple',
    source: 'questionnaire',
    type: 'boolean',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'questionnaire',
    legacyKey: 'couple.marketingConsent',
    aliases: ['marketing_permission', 'photo_marketing_consent', 'consent_marketing'],
    questionType: 'checkbox',
    aiAvailable: true,
    documentSection: 'additional',
    documentDataSource: 'wedding',
    documentValueType: 'boolean',
    sortOrder: 160,
  },
]
