import type { SystemVariableDef } from '@/lib/variables/registry/types'

/** Couple / bride / groom — questionnaire + CRM facing. */
export const COUPLE_VARIABLES: SystemVariableDef[] = [
  {
    id: 'bride_first_name',
    label: 'Imię Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.firstName',
    questionType: 'text',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 10,
  },
  {
    id: 'bride_last_name',
    label: 'Nazwisko Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.lastName',
    questionType: 'text',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 20,
  },
  {
    id: 'bride_phone',
    label: 'Telefon Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'phone',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.phone',
    questionType: 'phone',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 30,
  },
  {
    id: 'bride_email',
    label: 'E-mail Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'email',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.email',
    questionType: 'email',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 40,
  },
  {
    id: 'bride_address',
    label: 'Adres Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.address',
    questionType: 'textarea',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 50,
  },
  {
    id: 'bride_pesel',
    label: 'PESEL Panny Młodej',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'bride.pesel',
    aliases: ['pesel'],
    questionType: 'text',
    documentSection: 'bride',
    documentDataSource: 'wedding',
    sortOrder: 55,
  },
  {
    id: 'groom_first_name',
    label: 'Imię Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.firstName',
    questionType: 'text',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 110,
  },
  {
    id: 'groom_last_name',
    label: 'Nazwisko Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.lastName',
    questionType: 'text',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 120,
  },
  {
    id: 'groom_phone',
    label: 'Telefon Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'phone',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.phone',
    questionType: 'phone',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 130,
  },
  {
    id: 'groom_email',
    label: 'E-mail Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'email',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.email',
    questionType: 'email',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 140,
  },
  {
    id: 'groom_address',
    label: 'Adres Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.address',
    questionType: 'textarea',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 150,
  },
  {
    id: 'groom_pesel',
    label: 'PESEL Pana Młodego',
    category: 'couple',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'groom.pesel',
    questionType: 'text',
    documentSection: 'groom',
    documentDataSource: 'wedding',
    sortOrder: 155,
  },
]
