import type { SystemVariableDef } from '@/lib/variables/registry/types'

type PkgInput = {
  id: string
  label: string
  labelEn?: string
  description?: string
  legacyKey: string
  type?: SystemVariableDef['type']
  aliases?: string[]
  sortOrder: number
  /** Couple picks package in questionnaire. */
  questionnaireAvailable?: boolean
}

function pkg(input: PkgInput): SystemVariableDef {
  return {
    id: input.id,
    label: input.label,
    labelEn: input.labelEn,
    description: input.description,
    category: 'package',
    source: 'package',
    type: input.type ?? 'string',
    questionnaireAvailable: input.questionnaireAvailable ?? false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'package',
    legacyKey: input.legacyKey,
    aliases: input.aliases,
    documentSection: 'package',
    documentDataSource: 'package_snapshot',
    documentValueType:
      input.type === 'money' ||
      input.type === 'number' ||
      input.type === 'boolean'
        ? input.type
        : 'string',
    sortOrder: input.sortOrder,
    questionType: input.questionnaireAvailable ? 'select' : undefined,
    aiAvailable: true,
  }
}

/** Package / commercial contract slots — values from wedding commercial snapshot. */
export const PACKAGE_VARIABLES: SystemVariableDef[] = [
  pkg({
    id: 'package_name',
    label: 'Nazwa pakietu',
    description: 'Exact wedding.packageName snapshot (unchanged).',
    legacyKey: 'package.name',
    aliases: ['package'],
    sortOrder: 310,
    questionnaireAvailable: true,
  }),
  pkg({
    id: 'package_name_without_prefix',
    label: 'Nazwa pakietu (bez „Pakiet”)',
    description:
      'Presentation-only: strips one leading „Pakiet ” for templates that already say „Pakiecie …”.',
    legacyKey: 'package.nameWithoutPrefix',
    sortOrder: 311,
  }),
  pkg({
    id: 'contract_value',
    label: 'Wartość umowy (liczba)',
    description: 'Raw integer contractValue from wedding.price.',
    legacyKey: 'package.contractValueRaw',
    type: 'number',
    sortOrder: 318,
  }),
  pkg({
    id: 'contract_value_formatted',
    label: 'Wartość umowy',
    description: 'Formatted PLN, e.g. „9 500 zł”.',
    legacyKey: 'package.contractValueFormatted',
    type: 'money',
    sortOrder: 319,
  }),
  pkg({
    id: 'contract_value_words',
    label: 'Wartość umowy (słownie)',
    description: 'Polish amount in words for contractValue.',
    legacyKey: 'package.contractValueWords',
    sortOrder: 319.5,
  }),
  pkg({
    id: 'package_price',
    label: 'Wartość umowy (alias)',
    description:
      'LEGACY ALIAS → contract_value_formatted. Prefer contract_value_formatted.',
    legacyKey: 'package.price',
    type: 'money',
    aliases: ['contract_price', 'price'],
    sortOrder: 320,
  }),
  pkg({
    id: 'agreed_deposit',
    label: 'Zadatek uzgodniony (liczba)',
    description: 'Raw agreedDeposit from wedding.depositAmount.',
    legacyKey: 'package.agreedDepositRaw',
    type: 'number',
    sortOrder: 328,
  }),
  pkg({
    id: 'agreed_deposit_formatted',
    label: 'Zadatek uzgodniony',
    description: 'Formatted PLN for agreedDeposit.',
    legacyKey: 'package.agreedDepositFormatted',
    type: 'money',
    sortOrder: 329,
  }),
  pkg({
    id: 'agreed_deposit_words',
    label: 'Zadatek uzgodniony (słownie)',
    legacyKey: 'package.agreedDepositWords',
    sortOrder: 329.5,
  }),
  pkg({
    id: 'deposit_amount',
    label: 'Zadatek (alias)',
    description:
      'LEGACY ALIAS → agreed_deposit_formatted. Prefer agreed_deposit_formatted.',
    legacyKey: 'package.deposit',
    type: 'money',
    aliases: ['deposit'],
    sortOrder: 330,
  }),
  pkg({
    id: 'deposit_type',
    label: 'Typ zadatku',
    legacyKey: 'package.depositType',
    sortOrder: 335,
  }),
  pkg({
    id: 'deposit_percent',
    label: 'Zadatek (%)',
    legacyKey: 'package.depositPercent',
    type: 'number',
    sortOrder: 336,
  }),
  pkg({
    id: 'total_paid_formatted',
    label: 'Suma wpłat (sformatowana)',
    description: 'Formatted PLN for totalPaid (sum of paid payments).',
    legacyKey: 'package.totalPaidFormatted',
    type: 'money',
    sortOrder: 337,
  }),
  pkg({
    id: 'total_paid_words',
    label: 'Suma wpłat (słownie)',
    legacyKey: 'package.totalPaidWords',
    sortOrder: 337.5,
  }),
  pkg({
    id: 'remaining_to_pay',
    label: 'Pozostało do zapłaty (liczba)',
    description: 'contractValue − totalPaid (raw).',
    legacyKey: 'package.remainingToPayRaw',
    type: 'number',
    sortOrder: 338,
  }),
  pkg({
    id: 'remaining_to_pay_formatted',
    label: 'Pozostało do zapłaty',
    description: 'Formatted PLN for remainingToPay.',
    legacyKey: 'package.remainingToPayFormatted',
    type: 'money',
    sortOrder: 338.5,
  }),
  pkg({
    id: 'remaining_to_pay_words',
    label: 'Pozostało do zapłaty (słownie)',
    legacyKey: 'package.remainingToPayWords',
    sortOrder: 338.7,
  }),
  pkg({
    id: 'remaining_after_deposit',
    label: 'Po zaliczce (liczba)',
    description: 'contractValue − agreedDeposit (raw). Not payment-ledger based.',
    legacyKey: 'package.remainingAfterDepositRaw',
    type: 'number',
    sortOrder: 339,
  }),
  pkg({
    id: 'remaining_after_deposit_formatted',
    label: 'Po zaliczce uzgodnionej',
    description: 'Formatted PLN for remainingAfterDeposit.',
    legacyKey: 'package.remainingAfterDepositFormatted',
    type: 'money',
    sortOrder: 339.5,
  }),
  pkg({
    id: 'remaining_after_deposit_words',
    label: 'Po zaliczce (słownie)',
    legacyKey: 'package.remainingAfterDepositWords',
    sortOrder: 339.7,
  }),
  pkg({
    id: 'remaining_payment',
    label: 'Pozostała płatność (alias)',
    description:
      'LEGACY ALIAS → remaining_after_deposit_formatted (contractValue − agreedDeposit). NOT remainingToPay.',
    legacyKey: 'package.remaining',
    type: 'money',
    sortOrder: 340,
  }),
  pkg({
    id: 'payment_deadline',
    label: 'Termin płatności',
    legacyKey: 'package.paymentDeadline',
    aliases: ['payment_due_days'],
    sortOrder: 350,
  }),
  pkg({
    id: 'payment_installments',
    label: 'Liczba rat',
    legacyKey: 'package.installments',
    type: 'number',
    sortOrder: 360,
  }),
  pkg({
    id: 'delivery_time',
    label: 'Termin dostawy',
    description:
      'LEGACY — prefer delivery_term_text for Polish prose. Kept for older templates.',
    legacyKey: 'package.deliveryTime',
    aliases: ['delivery_deadline'],
    sortOrder: 370,
  }),
  pkg({
    id: 'delivery_months',
    label: 'Termin oddania (miesiące)',
    description: 'Raw deliveryMonths from wedding snapshot.',
    legacyKey: 'package.deliveryMonths',
    type: 'number',
    sortOrder: 370.2,
  }),
  pkg({
    id: 'delivery_days',
    label: 'Termin oddania (dni)',
    description: 'Raw deliveryDays from wedding snapshot.',
    legacyKey: 'package.deliveryDays',
    type: 'number',
    sortOrder: 370.3,
  }),
  pkg({
    id: 'delivery_term_text',
    label: 'Termin oddania (tekst)',
    description:
      'Polish delivery term from months or days (e.g. „4 miesiące”). Never from DOCX.',
    legacyKey: 'package.deliveryTermText',
    sortOrder: 370.4,
  }),
  pkg({
    id: 'included_services',
    label: 'Usługi w pakiecie',
    description:
      'Plain-text fallback from wedding.packageItems snapshot (never live catalog).',
    legacyKey: 'package.includedServices',
    sortOrder: 380,
  }),
  pkg({
    id: 'included_services_text',
    label: 'Usługi w pakiecie (tekst)',
    description: 'Same as included_services — explicit text key for contracts.',
    legacyKey: 'package.includedServicesText',
    sortOrder: 381,
  }),
  pkg({
    id: 'package_items_count',
    label: 'Liczba pozycji pakietu',
    description: 'Count of enabled wedding.packageItems snapshot lines.',
    legacyKey: 'package.itemsCount',
    type: 'number',
    sortOrder: 382,
  }),
  pkg({
    id: 'photographers_count',
    label: 'Liczba fotografów',
    legacyKey: 'package.photographersCount',
    type: 'number',
    sortOrder: 390,
  }),
  pkg({
    id: 'videographers_count',
    label: 'Liczba wideografów',
    legacyKey: 'package.videographersCount',
    type: 'number',
    sortOrder: 391,
  }),
  pkg({
    id: 'coverage_hours',
    label: 'Godziny reportażu',
    description: 'Raw coverageHours from wedding snapshot.',
    legacyKey: 'package.coverageHours',
    type: 'number',
    aliases: ['working_hours'],
    sortOrder: 392,
  }),
  pkg({
    id: 'coverage_end_time',
    label: 'Koniec reportażu (godzina)',
    description: 'Wedding snapshot coverageEndTime, e.g. „00:30”.',
    legacyKey: 'package.coverageEndTime',
    type: 'string',
    sortOrder: 392.5,
  }),
  pkg({
    id: 'overtime_price',
    label: 'Cena za godzinę nadliczbową',
    description: 'LEGACY — prefer overtime_rate_formatted.',
    legacyKey: 'package.overtimePrice',
    type: 'money',
    sortOrder: 393,
  }),
  pkg({
    id: 'overtime_rate',
    label: 'Stawka nadgodzin (liczba)',
    description: 'Raw overtimeRate from wedding snapshot.',
    legacyKey: 'package.overtimeRate',
    type: 'number',
    sortOrder: 393.5,
  }),
  pkg({
    id: 'overtime_rate_formatted',
    label: 'Stawka nadgodzin',
    description: 'Formatted PLN for overtimeRate.',
    legacyKey: 'package.overtimeRateFormatted',
    type: 'money',
    sortOrder: 393.6,
  }),
  pkg({
    id: 'overtime_rate_words',
    label: 'Stawka nadgodzin (słownie)',
    legacyKey: 'package.overtimeRateWords',
    sortOrder: 393.7,
  }),
  pkg({
    id: 'final_payment_due_date',
    label: 'Termin płatności końcowej',
    description: 'Wedding finalPaymentDueDate as DD.MM.YYYY.',
    legacyKey: 'package.finalPaymentDueDate',
    type: 'date',
    sortOrder: 351,
  }),
  pkg({
    id: 'final_payment_due_date_long',
    label: 'Termin płatności końcowej (słownie)',
    description: 'Long Polish date, e.g. „10 lipca 2026 r.”.',
    legacyKey: 'package.finalPaymentDueDateLong',
    type: 'date',
    sortOrder: 352,
  }),
  pkg({
    id: 'mileage_limit',
    label: 'Limit kilometrów',
    legacyKey: 'package.mileageLimit',
    type: 'number',
    aliases: ['included_distance'],
    sortOrder: 394,
  }),
  pkg({
    id: 'mileage_price',
    label: 'Cena za km',
    legacyKey: 'package.mileagePrice',
    type: 'money',
    sortOrder: 395,
  }),
  pkg({
    id: 'accommodation',
    label: 'Nocleg',
    legacyKey: 'package.accommodation',
    sortOrder: 396,
  }),
  pkg({
    id: 'travel_fee',
    label: 'Opłata za dojazd',
    legacyKey: 'package.travelFee',
    type: 'money',
    sortOrder: 397,
  }),
  pkg({
    id: 'album_included',
    label: 'Album w cenie',
    legacyKey: 'package.albumIncluded',
    type: 'boolean',
    sortOrder: 398,
  }),
  pkg({
    id: 'usb_included',
    label: 'Pendrive w cenie',
    legacyKey: 'package.usbIncluded',
    type: 'boolean',
    sortOrder: 399,
  }),
  pkg({
    id: 'online_gallery',
    label: 'Galeria online',
    legacyKey: 'package.onlineGallery',
    type: 'boolean',
    sortOrder: 400,
  }),
  pkg({
    id: 'engagement_session',
    label: 'Sesja narzeczeńska',
    legacyKey: 'package.engagementSession',
    type: 'boolean',
    sortOrder: 401,
  }),
  pkg({
    id: 'wedding_session',
    label: 'Sesja ślubna',
    legacyKey: 'package.weddingSession',
    type: 'boolean',
    sortOrder: 402,
  }),
  pkg({
    id: 'number_of_revisions',
    label: 'Liczba poprawek',
    legacyKey: 'package.revisions',
    type: 'number',
    sortOrder: 403,
  }),
  pkg({
    id: 'assistants',
    label: 'Asystenci',
    legacyKey: 'package.assistants',
    type: 'number',
    sortOrder: 404,
  }),

  // —— Recurring film / production slots (promoted from possibleVariables) ——
  pkg({
    id: 'drone_included',
    label: 'Dron w pakiecie',
    labelEn: 'Drone included',
    legacyKey: 'package.droneIncluded',
    type: 'boolean',
    aliases: ['drone', 'drone_operator', 'includes_drone'],
    sortOrder: 410,
  }),
  pkg({
    id: 'film_duration',
    label: 'Długość filmu',
    labelEn: 'Film duration',
    legacyKey: 'package.filmDuration',
    type: 'string',
    aliases: ['video_duration', 'film_length', 'movie_duration'],
    sortOrder: 411,
  }),
  pkg({
    id: 'film_delivery_method',
    label: 'Sposób dostarczenia filmu',
    labelEn: 'Film delivery method',
    legacyKey: 'package.filmDeliveryMethod',
    type: 'string',
    aliases: ['video_delivery_method', 'delivery_method_film'],
    sortOrder: 412,
  }),
  pkg({
    id: 'film_delivery_format',
    label: 'Format dostarczenia filmu',
    labelEn: 'Film delivery format',
    legacyKey: 'package.filmDeliveryFormat',
    type: 'string',
    aliases: ['video_delivery_format', 'delivery_format'],
    sortOrder: 413,
  }),
  pkg({
    id: 'postproduction_duration',
    label: 'Czas postprodukcji',
    labelEn: 'Post-production duration',
    legacyKey: 'package.postproductionDuration',
    type: 'string',
    aliases: [
      'post_production_duration',
      'postproduction_time',
      'editing_duration',
      'editing_time',
    ],
    sortOrder: 414,
  }),
]
