import type { SystemVariableDef } from '@/lib/variables/registry/types'

export const WEDDING_VARIABLES: SystemVariableDef[] = [
  {
    id: 'wedding_date',
    label: 'Data ślubu',
    category: 'wedding',
    source: 'questionnaire',
    type: 'date',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'wedding',
    legacyKey: 'wedding.date',
    questionType: 'date',
    documentSection: 'wedding',
    documentDataSource: 'wedding',
    documentValueType: 'date',
    sortOrder: 210,
  },
  {
    id: 'ceremony_time',
    label: 'Godzina ceremonii',
    category: 'wedding',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'wedding',
    legacyKey: 'wedding.ceremonyTime',
    questionType: 'text',
    documentSection: 'wedding',
    documentDataSource: 'wedding',
    sortOrder: 220,
  },
  {
    id: 'couple_names',
    label: 'Imiona pary',
    category: 'wedding',
    source: 'computed',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'computed',
    legacyKey: 'wedding.coupleNames',
    documentSection: 'wedding',
    documentDataSource: 'computed',
    sortOrder: 230,
  },
  {
    id: 'wedding_schedule',
    label: 'Harmonogram',
    category: 'wedding',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'wedding',
    legacyKey: 'wedding.schedule',
    aliases: ['schedule'],
    questionType: 'textarea',
    documentSection: 'wedding',
    documentDataSource: 'wedding',
    sortOrder: 240,
  },
  {
    id: 'preparation_location',
    label: 'Miejsce przygotowań',
    category: 'wedding',
    source: 'questionnaire',
    type: 'location',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'location.preparation',
    questionType: 'location',
    documentSection: 'locations',
    documentDataSource: 'wedding',
    sortOrder: 510,
  },
  {
    id: 'ceremony_location',
    label: 'Miejsce ceremonii',
    category: 'wedding',
    source: 'questionnaire',
    type: 'location',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'location.ceremony',
    questionType: 'location',
    documentSection: 'locations',
    documentDataSource: 'wedding',
    sortOrder: 520,
  },
  {
    id: 'reception_location',
    label: 'Miejsce wesela',
    category: 'wedding',
    source: 'questionnaire',
    type: 'location',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'questionnaire',
    legacyKey: 'location.reception',
    questionType: 'location',
    documentSection: 'locations',
    documentDataSource: 'wedding',
    sortOrder: 530,
  },
  {
    id: 'contract_number',
    label: 'Numer umowy',
    category: 'system',
    source: 'draft',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'draft',
    legacyKey: 'additional.contractNumber',
    documentSection: 'additional',
    documentDataSource: 'draft',
    sortOrder: 710,
  },
  {
    id: 'contract_city',
    label: 'Miasto',
    category: 'system',
    source: 'draft',
    type: 'string',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'draft',
    legacyKey: 'additional.city',
    documentSection: 'additional',
    documentDataSource: 'draft',
    sortOrder: 720,
  },
  {
    id: 'additional_notes',
    label: 'Uwagi',
    category: 'wedding',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'wedding',
    legacyKey: 'additional.notes',
    aliases: ['notes'],
    questionType: 'textarea',
    documentSection: 'additional',
    documentDataSource: 'wedding',
    sortOrder: 730,
  },

  // —— Recurring business concepts (promoted from possibleVariables) ——
  {
    id: 'wedding_planner_name',
    label: 'Imię i nazwisko wedding plannera',
    labelEn: 'Wedding planner name',
    category: 'wedding',
    source: 'questionnaire',
    type: 'string',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'questionnaire',
    legacyKey: 'wedding.plannerName',
    aliases: ['planner_name', 'wedding_planner'],
    questionType: 'text',
    aiAvailable: true,
    documentSection: 'additional',
    documentDataSource: 'wedding',
    sortOrder: 610,
  },
  {
    id: 'wedding_planner_phone',
    label: 'Telefon wedding plannera',
    labelEn: 'Wedding planner phone',
    category: 'wedding',
    source: 'questionnaire',
    type: 'phone',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'questionnaire',
    legacyKey: 'wedding.plannerPhone',
    aliases: ['planner_phone'],
    questionType: 'phone',
    aiAvailable: true,
    documentSection: 'additional',
    documentDataSource: 'wedding',
    sortOrder: 620,
  },
  {
    id: 'wedding_planner_email',
    label: 'E-mail wedding plannera',
    labelEn: 'Wedding planner email',
    category: 'wedding',
    source: 'questionnaire',
    type: 'email',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'questionnaire',
    legacyKey: 'wedding.plannerEmail',
    aliases: ['planner_email'],
    questionType: 'email',
    aiAvailable: true,
    documentSection: 'additional',
    documentDataSource: 'wedding',
    sortOrder: 630,
  },
  {
    id: 'food_for_crew',
    label: 'Wyżywienie ekipy',
    labelEn: 'Food for crew',
    description: 'Czy para zapewnia wyżywienie dla ekipy w dniu ślubu.',
    category: 'wedding',
    source: 'questionnaire',
    type: 'boolean',
    questionnaireAvailable: true,
    documentAvailable: true,
    crmAvailable: false,
    defaultProvider: 'questionnaire',
    legacyKey: 'wedding.foodForCrew',
    aliases: ['crew_food', 'food_for_team', 'meals_for_crew'],
    questionType: 'checkbox',
    aiAvailable: true,
    documentSection: 'additional',
    documentDataSource: 'wedding',
    documentValueType: 'boolean',
    sortOrder: 640,
  },

  {
    id: 'deposit_paid',
    label: 'Zadatek opłacony',
    category: 'crm',
    source: 'crm',
    type: 'boolean',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'crm',
    legacyKey: 'payments.depositPaid',
    documentSection: 'payments',
    documentDataSource: 'payments',
    documentValueType: 'boolean',
    sortOrder: 410,
  },
  {
    id: 'total_paid',
    label: 'Suma wpłat',
    category: 'crm',
    source: 'crm',
    type: 'money',
    questionnaireAvailable: false,
    documentAvailable: true,
    crmAvailable: true,
    defaultProvider: 'crm',
    legacyKey: 'payments.totalPaid',
    documentSection: 'payments',
    documentDataSource: 'payments',
    documentValueType: 'money',
    sortOrder: 420,
  },
]
