import type { ThemeTokenMap } from '@/features/theme/tokenKeys'

/**
 * Classic — current OurWed monochrome appearance (exact values from tokens.css).
 * Do not redesign. Reference: existing authenticated CRM UI.
 */
export const CLASSIC_TOKENS: ThemeTokenMap = {
  '--app-background': '#f7f7f7',
  '--app-background-subtle': '#efefef',
  '--app-background-raised': '#ffffff',

  '--surface-primary': '#ffffff',
  '--surface-secondary': '#fafafa',
  '--surface-tertiary': '#e8e8e8',
  '--surface-elevated': '#ffffff',
  '--surface-inverse': '#0a0a0a',
  '--surface-hover': '#fafafa',
  '--surface-selected': '#f0f0f0',

  '--sidebar-background': '#0a0a0a',
  '--sidebar-border': 'rgba(255, 255, 255, 0.08)',
  '--sidebar-text': 'rgba(255, 255, 255, 0.55)',
  '--sidebar-text-muted': 'rgba(255, 255, 255, 0.35)',
  '--sidebar-item-hover': 'rgba(255, 255, 255, 0.06)',
  '--sidebar-item-active-background': 'rgba(255, 255, 255, 0.1)',
  '--sidebar-item-active-text': '#ffffff',
  '--navigation-active-indicator': '#ffffff',

  '--text-primary': '#0a0a0a',
  '--text-secondary': '#5c5c5c',
  '--text-muted': '#8f8f8f',
  '--text-disabled': '#b0b0b0',
  '--text-inverse': '#ffffff',
  '--text-link': '#0a0a0a',
  '--text-link-hover': '#262626',

  '--border-subtle': 'rgba(0, 0, 0, 0.04)',
  '--border-default': 'rgba(0, 0, 0, 0.06)',
  '--border-strong': 'rgba(0, 0, 0, 0.1)',
  '--border-interactive': 'rgba(0, 0, 0, 0.14)',
  '--border-hover': 'rgba(0, 0, 0, 0.18)',

  '--brand-primary': '#0a0a0a',
  '--brand-primary-hover': '#262626',
  '--brand-primary-active': '#000000',
  '--brand-primary-text': '#ffffff',
  '--brand-primary-soft': '#f0f0f0',
  '--brand-primary-soft-text': '#0a0a0a',
  '--brand-secondary': '#737373',
  '--brand-secondary-hover': '#525252',
  '--brand-secondary-text': '#ffffff',

  '--button-primary-background': '#0a0a0a',
  '--button-primary-background-hover': '#262626',
  '--button-primary-background-active': '#000000',
  '--button-primary-text': '#ffffff',
  '--button-primary-border': 'transparent',
  '--button-secondary-background': '#ffffff',
  '--button-secondary-background-hover': '#fafafa',
  '--button-secondary-text': '#0a0a0a',
  '--button-secondary-border': 'rgba(0, 0, 0, 0.1)',
  '--button-ghost-background-hover': 'rgba(0, 0, 0, 0.04)',
  '--button-ghost-text': '#0a0a0a',

  '--input-background': '#ffffff',
  '--input-background-disabled': '#f5f5f5',
  '--input-border': 'rgba(0, 0, 0, 0.1)',
  '--input-border-hover': 'rgba(0, 0, 0, 0.16)',
  '--input-border-focus': '#0a0a0a',
  '--input-text': '#0a0a0a',
  '--input-placeholder': '#8f8f8f',
  '--input-selection': 'rgba(10, 10, 10, 0.12)',
  '--focus-ring': '0 0 0 3px rgba(10, 10, 10, 0.08)',
  '--focus-ring-strong': '0 0 0 3px rgba(10, 10, 10, 0.16)',

  '--tab-text': '#5c5c5c',
  '--tab-text-hover': '#0a0a0a',
  '--tab-text-active': '#0a0a0a',
  '--tab-background-hover': 'rgba(0, 0, 0, 0.04)',
  '--tab-background-active': '#ffffff',
  '--tab-border-active': '#0a0a0a',

  '--card-background': '#ffffff',
  '--card-background-hover': '#fafafa',
  '--card-border': 'rgba(0, 0, 0, 0.06)',
  '--card-border-hover': 'rgba(0, 0, 0, 0.1)',
  '--panel-background': '#ffffff',
  '--panel-border': 'rgba(0, 0, 0, 0.06)',

  '--badge-neutral-background': '#f0f0f0',
  '--badge-neutral-text': '#5c5c5c',
  '--badge-neutral-border': 'rgba(0, 0, 0, 0.06)',
  '--badge-accent-background': '#0a0a0a',
  '--badge-accent-text': '#ffffff',
  '--badge-accent-border': '#0a0a0a',

  '--overlay-background': 'rgba(0, 0, 0, 0.32)',
  '--dialog-background': '#ffffff',
  '--dialog-border': 'rgba(0, 0, 0, 0.06)',
  '--drawer-background': '#ffffff',
  '--tooltip-background': '#0a0a0a',
  '--tooltip-text': '#ffffff',
  '--popover-background': '#ffffff',
  '--popover-border': 'rgba(0, 0, 0, 0.08)',

  '--row-background': '#ffffff',
  '--row-background-hover': '#fafafa',
  '--row-background-selected': '#f0f0f0',
  '--row-border': 'rgba(0, 0, 0, 0.06)',
  '--table-header-background': '#f7f7f7',
  '--table-header-text': '#5c5c5c',

  '--calendar-today-background': '#f0f0f0',
  '--calendar-today-text': '#0a0a0a',
  '--calendar-event-background': '#0a0a0a',
  '--calendar-event-text': '#ffffff',
  '--timeline-line': 'rgba(0, 0, 0, 0.1)',
  '--timeline-node': '#8f8f8f',
  '--timeline-node-active': '#0a0a0a',

  '--separator': 'rgba(0, 0, 0, 0.06)',
  '--skeleton-background': '#efefef',
  '--skeleton-highlight': '#f7f7f7',
  '--selection-background': 'rgba(10, 10, 10, 0.12)',
  '--selection-text': '#0a0a0a',
  '--scrollbar-thumb': 'rgba(0, 0, 0, 0.2)',
  '--scrollbar-thumb-hover': 'rgba(0, 0, 0, 0.32)',

  '--shadow-xs': '0 1px 2px rgba(0, 0, 0, 0.04)',
  '--shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.04), 0 6px 16px rgba(0, 0, 0, 0.04)',
  '--shadow-md': '0 2px 6px rgba(0, 0, 0, 0.04), 0 14px 34px rgba(0, 0, 0, 0.06)',
  '--shadow-lg': '0 8px 20px rgba(0, 0, 0, 0.05), 0 28px 60px rgba(0, 0, 0, 0.08)',
  '--shadow-drawer': '-18px 0 48px rgba(0, 0, 0, 0.18)',
}
