import type { TravelPlan } from '@/types/travel'
import type {
  Notification,
  Task,
  Wedding,
} from '@/types/wedding'

export const DEMO_WEDDING_ID = 'demo-wedding-anna-michal'
export const DEMO_USER_NAME = 'Anna'

/** Single complete demo wedding used across the landing product preview. */
export const demoWedding: Wedding = {
  id: DEMO_WEDDING_ID,
  couple: {
    partner1: 'Anna Kowalska',
    partner2: 'Michał Kowalski',
    partner1FirstName: 'Anna',
    partner1LastName: 'Kowalska',
    partner2FirstName: 'Michał',
    partner2LastName: 'Kowalski',
    partner1Phone: '••• ••• •••',
    partner1Email: '••••••@gmail.com',
    partner1Address: '••••••••••••••••••••',
    partner1PostalCode: '••-•••',
    partner1City: 'Warszawa',
    partner2Phone: '••• ••• •••',
    partner2Email: '••••••@gmail.com',
    partner2Address: '••••••••••••••••••••',
    partner2PostalCode: '••-•••',
    partner2City: 'Warszawa',
    email: '••••••@gmail.com',
    phone: '••• ••• •••',
    venue: 'Pałac Mała Wieś',
    city: 'Grójec',
  },
  date: '2026-08-22',
  ceremonyTime: '14:30',
  status: 'active',
  workflowStage: 'preparation',
  packageName: 'Reportaż Premium',
  packageId: null,
  price: 8500,
  depositAmount: 3000,
  currency: 'PLN',
  preparationLocation: 'Hotel Bristol, Warszawa',
  ceremonyLocation: 'Kościół św. Anny, Warszawa',
  receptionLocation: 'Pałac Mała Wieś',
  accentColor: '#7c5cbf',
  createdAt: '2026-03-12T10:00:00.000Z',
  checklist: [
    { id: 'eq1', label: 'Aparat + zapasowe baterie', completed: true, category: 'camera' },
    { id: 'eq2', label: 'Obiektyw 35 mm / 85 mm', completed: true, category: 'camera' },
    { id: 'eq3', label: 'Lampy błyskowe', completed: false, category: 'light' },
  ],
  schedule: [
    { id: 's1', time: '10:00', title: 'Przyjazd do Panny Młodej', location: 'Hotel Bristol, Warszawa' },
    { id: 's2', time: '11:45', title: 'Przyjazd do Pana Młodego', location: 'Hotel Verte, Warszawa' },
    { id: 's3', time: '13:00', title: 'First Look', location: 'Ogród Saski' },
    { id: 's4', time: '14:30', title: 'Ceremonia', location: 'Kościół św. Anny, Warszawa' },
    { id: 's5', time: '16:00', title: 'Życzenia', location: 'Pałac Mała Wieś' },
    { id: 's6', time: '17:00', title: 'Obiad', location: 'Pałac Mała Wieś' },
    { id: 's7', time: '18:30', title: 'Sesja', location: 'Park przy pałacu' },
    { id: 's8', time: '20:00', title: 'Pierwszy taniec', location: 'Pałac Mała Wieś' },
    { id: 's9', time: '22:00', title: 'Tort', location: 'Pałac Mała Wieś' },
  ],
  payments: [
    {
      id: 'p1',
      label: 'Zadatek',
      amount: 3000,
      type: 'deposit',
      paid: true,
      paidAt: '2026-04-02',
      dueDate: '2026-04-01',
      method: 'transfer',
    },
    {
      id: 'p2',
      label: 'Płatność końcowa',
      amount: 5500,
      type: 'final',
      paid: false,
      dueDate: '2026-08-15',
      method: 'transfer',
    },
  ],
  finances: [],
  questionnaires: {
    contractData: {
      status: 'completed',
      sentAt: '2026-03-15',
      completedAt: '2026-03-18',
    },
    weddingQuestionnaire: {
      status: 'completed',
      sentAt: '2026-06-01',
      completedAt: '2026-06-20',
    },
  },
  contract: {
    status: 'signed',
    generatedAt: '2026-03-20',
    sentAt: '2026-03-21',
    signedAt: '2026-03-28',
  },
  notes: [
    {
      id: 'n1',
      content: 'Para prosi o dyskretne ujęcia podczas ceremonii. Tort o 22:00.',
      createdAt: '2026-06-21T12:00:00.000Z',
      author: 'System',
      badge: 'Ankieta ślubna',
      source: 'wedding_questionnaire',
    },
  ],
  deliverables: [
    {
      id: 'd1',
      name: 'Teaser wideo',
      source: 'package',
      completed: false,
      deliveryDate: '2026-09-05',
    },
    {
      id: 'd2',
      name: 'Galeria online',
      source: 'package',
      completed: false,
      deliveryDate: '2026-10-15',
    },
  ],
  timeline: [
    {
      id: 't1',
      title: 'Rezerwacja utworzona',
      date: '2026-03-12',
      type: 'created',
      description: 'Nowe zlecenie Anna & Michał',
    },
    {
      id: 't2',
      title: 'Ankieta umowy ukończona',
      date: '2026-03-18',
      type: 'questionnaire_completed',
    },
    {
      id: 't3',
      title: 'Umowa podpisana',
      date: '2026-03-28',
      type: 'contract_signed',
    },
    {
      id: 't4',
      title: 'Zadatek otrzymany',
      date: '2026-04-02',
      type: 'payment_received',
      description: '3 000 zł',
    },
    {
      id: 't5',
      title: 'Ankieta ślubna ukończona',
      date: '2026-06-20',
      type: 'questionnaire_completed',
    },
  ],
}

export const demoWeddings: Wedding[] = [demoWedding]

/** All wedding tasks shown on Wedding Detail (completed + pending). */
export const demoWeddingTasks: Task[] = [
  {
    id: 'wt-1',
    weddingId: DEMO_WEDDING_ID,
    title: 'Wysłano ankietę',
    dueDate: '2026-03-15',
    completed: true,
    priority: 'medium',
  },
  {
    id: 'wt-2',
    weddingId: DEMO_WEDDING_ID,
    title: 'Podpisano umowę',
    dueDate: '2026-03-28',
    completed: true,
    priority: 'high',
  },
  {
    id: 'wt-3',
    weddingId: DEMO_WEDDING_ID,
    title: 'Opłacono zaliczkę',
    dueDate: '2026-04-02',
    completed: true,
    priority: 'high',
  },
  {
    id: 'wt-4',
    weddingId: DEMO_WEDDING_ID,
    title: 'Dodano lokalizacje',
    dueDate: '2026-06-01',
    completed: true,
    priority: 'medium',
  },
  {
    id: 'wt-5',
    weddingId: DEMO_WEDDING_ID,
    title: 'Oddać teaser',
    dueDate: '2026-09-05',
    completed: false,
    priority: 'high',
  },
  {
    id: 'wt-6',
    weddingId: DEMO_WEDDING_ID,
    title: 'Oddać galerię',
    dueDate: '2026-10-15',
    completed: false,
    priority: 'medium',
  },
]

export const demoTasks: Task[] = [
  {
    id: 'task-1',
    weddingId: DEMO_WEDDING_ID,
    title: 'Oddać teaser',
    dueDate: '2026-09-05',
    completed: false,
    priority: 'high',
  },
  {
    id: 'task-2',
    weddingId: DEMO_WEDDING_ID,
    title: 'Oddać galerię',
    dueDate: '2026-10-15',
    completed: false,
    priority: 'medium',
  },
  {
    id: 'task-3',
    weddingId: DEMO_WEDDING_ID,
    title: 'Potwierdzić dojazd do Pałacu Mała Wieś',
    dueDate: '2026-08-20',
    completed: false,
    priority: 'medium',
  },
]

export const demoNotifications: Notification[] = [
  {
    id: 'n-1',
    title: 'Ankieta ślubna ukończona',
    message: 'Anna & Michał uzupełnili ankietę przedślubną.',
    createdAt: new Date().toISOString(),
    read: false,
    type: 'success',
  },
  {
    id: 'n-2',
    title: 'Zbliża się ślub',
    message: 'Za kilka tygodni: Anna & Michał · 22 sie 2026',
    createdAt: new Date().toISOString(),
    read: false,
    type: 'info',
  },
  {
    id: 'n-3',
    title: 'Płatność końcowa',
    message: 'Pozostało 5 500 zł — termin 15 sie 2026',
    createdAt: new Date().toISOString(),
    read: true,
    type: 'warning',
  },
]

/** Precomputed travel plan: Studio → Przygotowania → Ceremonia → Przyjęcie */
export const demoTravelPlan: TravelPlan = {
  weddingId: DEMO_WEDDING_ID,
  studio: {
    id: 'demo-studio',
    userId: 'demo-user',
    studioName: 'Studio OurWed',
    street: 'ul. Mokotowska',
    buildingNumber: '12',
    postalCode: '00-561',
    city: 'Warszawa',
    country: 'PL',
    formattedAddress: 'ul. Mokotowska 12, 00-561 Warszawa',
    latitude: 52.2194,
    longitude: 21.0172,
    placeId: 'demo-studio-place',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  places: [
    {
      id: 'place-prep',
      weddingId: DEMO_WEDDING_ID,
      role: 'preparation',
      label: 'Hotel Bristol',
      placeId: 'demo-bristol',
      formattedAddress: 'Hotel Bristol, Krakowskie Przedmieście 42/44, Warszawa',
      latitude: 52.2419,
      longitude: 21.0153,
      sortOrder: 0,
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-06-01T00:00:00.000Z',
    },
    {
      id: 'place-ceremony',
      weddingId: DEMO_WEDDING_ID,
      role: 'ceremony',
      label: 'Kościół św. Anny',
      placeId: 'demo-anna',
      formattedAddress: 'Kościół św. Anny, Krakowskie Przedmieście 68, Warszawa',
      latitude: 52.2472,
      longitude: 21.0141,
      sortOrder: 1,
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-06-01T00:00:00.000Z',
    },
    {
      id: 'place-reception',
      weddingId: DEMO_WEDDING_ID,
      role: 'reception',
      label: 'Pałac Mała Wieś',
      placeId: 'demo-palac',
      formattedAddress: 'Pałac Mała Wieś, Mała Wieś, gm. Grójec',
      latitude: 51.8655,
      longitude: 20.8512,
      sortOrder: 2,
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-06-01T00:00:00.000Z',
    },
  ],
  segments: [
    {
      id: 'seg-1',
      weddingId: DEMO_WEDDING_ID,
      sequence: 0,
      originKind: 'studio',
      originWeddingPlaceId: null,
      destinationKind: 'wedding_place',
      destinationWeddingPlaceId: 'place-prep',
      endpointsHash: 'demo-1',
      distanceMeters: 4200,
      distanceText: '4,2 km',
      durationSeconds: 14 * 60,
      durationText: '14 min',
      travelMode: 'DRIVE',
      provider: 'demo',
      status: 'ok',
      errorMessage: null,
      calculatedAt: '2026-07-01T00:00:00.000Z',
      createdAt: '2026-07-01T00:00:00.000Z',
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'seg-2',
      weddingId: DEMO_WEDDING_ID,
      sequence: 1,
      originKind: 'wedding_place',
      originWeddingPlaceId: 'place-prep',
      destinationKind: 'wedding_place',
      destinationWeddingPlaceId: 'place-ceremony',
      endpointsHash: 'demo-2',
      distanceMeters: 900,
      distanceText: '0,9 km',
      durationSeconds: 5 * 60,
      durationText: '5 min',
      travelMode: 'DRIVE',
      provider: 'demo',
      status: 'ok',
      errorMessage: null,
      calculatedAt: '2026-07-01T00:00:00.000Z',
      createdAt: '2026-07-01T00:00:00.000Z',
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'seg-3',
      weddingId: DEMO_WEDDING_ID,
      sequence: 2,
      originKind: 'wedding_place',
      originWeddingPlaceId: 'place-ceremony',
      destinationKind: 'wedding_place',
      destinationWeddingPlaceId: 'place-reception',
      endpointsHash: 'demo-3',
      distanceMeters: 48_000,
      distanceText: '48 km',
      durationSeconds: 52 * 60,
      durationText: '52 min',
      travelMode: 'DRIVE',
      provider: 'demo',
      status: 'ok',
      errorMessage: null,
      calculatedAt: '2026-07-01T00:00:00.000Z',
      createdAt: '2026-07-01T00:00:00.000Z',
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
  ],
  hasError: false,
  errorMessage: null,
}

/** Masked contract meta shown in demo overview (not a full PESEL field in Wedding). */
export const demoMaskedMeta = {
  contractNumber: '••••••',
  peselBride: '•••••••••••',
  peselGroom: '•••••••••••',
  groomPrep: 'Hotel Verte, Warszawa',
} as const

/** Sample questionnaire answers for the completed wedding questionnaire. */
export const demoQuestionnaireAnswers: Record<string, string> = {
  'Pierwszy taniec': 'Walc wiedeński — „Moon River”',
  'Kolory przewodnie': 'Szampański i zieleń oliwkowa',
  'Sesja plenerowa': 'Park przy Pałacu Mała Wieś, około 18:30',
  'Uwagi dla fotografów / zespołu':
    'Prosimy o dyskretne ujęcia przy ołtarzu. Tort o 22:00 — ważny moment rodzinny.',
  'Przygotowania Panny Młodej': 'Hotel Bristol, Warszawa',
  'Przygotowania Pana Młodego': 'Hotel Verte, Warszawa',
}
