/**
 * Central Variable Registry (app-side mirror of document_variable_registry).
 * All document types bind slots to these keys. Users never see placeholders.
 * Polish labels here are the only labels shown in review / questionnaires.
 */

import type {
  DocumentVariableDef,
  DocumentVariableSection,
} from '@/types/documents'

export const DOCUMENT_VARIABLE_SECTIONS: {
  id: DocumentVariableSection
  label: string
}[] = [
  { id: 'bride', label: 'Panna młoda' },
  { id: 'groom', label: 'Pan młody' },
  { id: 'wedding', label: 'Ślub' },
  { id: 'package', label: 'Pakiet' },
  { id: 'payments', label: 'Płatności' },
  { id: 'locations', label: 'Lokalizacje' },
  { id: 'studio', label: 'Studio' },
  { id: 'additional', label: 'Dodatkowe' },
  { id: 'template', label: 'Wartości z umowy' },
]

/** System variables — keep in sync with migration seed. */
export const DOCUMENT_VARIABLES: DocumentVariableDef[] = [
  {
    key: 'bride.firstName',
    section: 'bride',
    labelPl: 'Imię Panny Młodej',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 10,
  },
  {
    key: 'bride.lastName',
    section: 'bride',
    labelPl: 'Nazwisko Panny Młodej',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 20,
  },
  {
    key: 'bride.phone',
    section: 'bride',
    labelPl: 'Telefon Panny Młodej',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 30,
  },
  {
    key: 'bride.email',
    section: 'bride',
    labelPl: 'E-mail Panny Młodej',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 40,
  },
  {
    key: 'bride.address',
    section: 'bride',
    labelPl: 'Adres Panny Młodej',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 50,
  },
  {
    key: 'groom.firstName',
    section: 'groom',
    labelPl: 'Imię Pana Młodego',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 110,
  },
  {
    key: 'groom.lastName',
    section: 'groom',
    labelPl: 'Nazwisko Pana Młodego',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 120,
  },
  {
    key: 'groom.phone',
    section: 'groom',
    labelPl: 'Telefon Pana Młodego',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 130,
  },
  {
    key: 'groom.email',
    section: 'groom',
    labelPl: 'E-mail Pana Młodego',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 140,
  },
  {
    key: 'groom.address',
    section: 'groom',
    labelPl: 'Adres Pana Młodego',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 150,
  },
  {
    key: 'wedding.date',
    section: 'wedding',
    labelPl: 'Data ślubu',
    valueType: 'date',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 210,
  },
  {
    key: 'wedding.ceremonyTime',
    section: 'wedding',
    labelPl: 'Godzina ceremonii',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 220,
  },
  {
    key: 'wedding.coupleNames',
    section: 'wedding',
    labelPl: 'Imiona pary',
    valueType: 'string',
    dataSource: 'computed',
    isSystem: true,
    sortOrder: 230,
  },
  {
    key: 'package.name',
    section: 'package',
    labelPl: 'Pakiet',
    valueType: 'string',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 310,
  },
  {
    key: 'package.price',
    section: 'package',
    labelPl: 'Wartość umowy',
    valueType: 'money',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 320,
  },
  {
    key: 'package.deposit',
    section: 'package',
    labelPl: 'Zadatek',
    valueType: 'money',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 330,
  },
  {
    key: 'package.depositType',
    section: 'package',
    labelPl: 'Typ zadatku',
    valueType: 'string',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 335,
  },
  {
    key: 'package.depositPercent',
    section: 'package',
    labelPl: 'Zadatek (%)',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 336,
  },
  {
    key: 'package.remaining',
    section: 'package',
    labelPl: 'Pozostała płatność',
    valueType: 'money',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 340,
  },
  {
    key: 'package.paymentDeadline',
    section: 'package',
    labelPl: 'Termin płatności',
    valueType: 'string',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 350,
  },
  {
    key: 'package.installments',
    section: 'package',
    labelPl: 'Liczba rat',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 360,
  },
  {
    key: 'package.deliveryTime',
    section: 'package',
    labelPl: 'Termin dostawy',
    valueType: 'string',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 370,
  },
  {
    key: 'package.includedServices',
    section: 'package',
    labelPl: 'Usługi w pakiecie',
    valueType: 'string',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 380,
  },
  {
    key: 'package.photographersCount',
    section: 'package',
    labelPl: 'Liczba fotografów',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 390,
  },
  {
    key: 'package.videographersCount',
    section: 'package',
    labelPl: 'Liczba wideografów',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 391,
  },
  {
    key: 'package.workingHours',
    section: 'package',
    labelPl: 'Godziny pracy',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 392,
  },
  {
    key: 'package.overtimePrice',
    section: 'package',
    labelPl: 'Cena za godzinę nadliczbową',
    valueType: 'money',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 393,
  },
  {
    key: 'package.mileageLimit',
    section: 'package',
    labelPl: 'Limit kilometrów',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 394,
  },
  {
    key: 'package.mileagePrice',
    section: 'package',
    labelPl: 'Cena za km',
    valueType: 'money',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 395,
  },
  {
    key: 'package.accommodation',
    section: 'package',
    labelPl: 'Nocleg',
    valueType: 'string',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 396,
  },
  {
    key: 'package.travelFee',
    section: 'package',
    labelPl: 'Opłata za dojazd',
    valueType: 'money',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 397,
  },
  {
    key: 'package.albumIncluded',
    section: 'package',
    labelPl: 'Album w cenie',
    valueType: 'boolean',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 398,
  },
  {
    key: 'package.usbIncluded',
    section: 'package',
    labelPl: 'Pendrive w cenie',
    valueType: 'boolean',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 399,
  },
  {
    key: 'package.onlineGallery',
    section: 'package',
    labelPl: 'Galeria online',
    valueType: 'boolean',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 400,
  },
  {
    key: 'package.engagementSession',
    section: 'package',
    labelPl: 'Sesja narzeczeńska',
    valueType: 'boolean',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 401,
  },
  {
    key: 'package.weddingSession',
    section: 'package',
    labelPl: 'Sesja ślubna',
    valueType: 'boolean',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 402,
  },
  {
    key: 'package.revisions',
    section: 'package',
    labelPl: 'Liczba poprawek',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 403,
  },
  {
    key: 'package.assistants',
    section: 'package',
    labelPl: 'Asystenci',
    valueType: 'number',
    dataSource: 'package_snapshot',
    isSystem: true,
    sortOrder: 404,
  },
  {
    key: 'payments.depositPaid',
    section: 'payments',
    labelPl: 'Zadatek opłacony',
    valueType: 'boolean',
    dataSource: 'payments',
    isSystem: true,
    sortOrder: 410,
  },
  {
    key: 'payments.totalPaid',
    section: 'payments',
    labelPl: 'Suma wpłat',
    valueType: 'money',
    dataSource: 'payments',
    isSystem: true,
    sortOrder: 420,
  },
  {
    key: 'location.preparation',
    section: 'locations',
    labelPl: 'Miejsce przygotowań',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 510,
  },
  {
    key: 'location.ceremony',
    section: 'locations',
    labelPl: 'Miejsce ceremonii',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 520,
  },
  {
    key: 'location.reception',
    section: 'locations',
    labelPl: 'Miejsce wesela',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 530,
  },
  {
    key: 'studio.name',
    section: 'studio',
    labelPl: 'Nazwa studia',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 610,
  },
  {
    key: 'studio.photographerName',
    section: 'studio',
    labelPl: 'Imię fotografa',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 615,
  },
  {
    key: 'studio.address',
    section: 'studio',
    labelPl: 'Adres firmy',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 620,
  },
  {
    key: 'studio.nip',
    section: 'studio',
    labelPl: 'NIP',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 630,
  },
  {
    key: 'studio.regon',
    section: 'studio',
    labelPl: 'REGON',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 640,
  },
  {
    key: 'studio.bankAccount',
    section: 'studio',
    labelPl: 'Numer konta',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 650,
  },
  {
    key: 'studio.email',
    section: 'studio',
    labelPl: 'E-mail studia',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 660,
  },
  {
    key: 'studio.phone',
    section: 'studio',
    labelPl: 'Telefon studia',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 670,
  },
  {
    key: 'studio.website',
    section: 'studio',
    labelPl: 'Strona WWW',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 680,
  },
  {
    key: 'studio.logo',
    section: 'studio',
    labelPl: 'Logo',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 690,
  },
  {
    key: 'additional.contractNumber',
    section: 'additional',
    labelPl: 'Numer umowy',
    valueType: 'string',
    dataSource: 'draft',
    isSystem: true,
    sortOrder: 710,
  },
  {
    key: 'additional.city',
    section: 'additional',
    labelPl: 'Miasto',
    valueType: 'string',
    dataSource: 'draft',
    isSystem: true,
    sortOrder: 720,
  },
  {
    key: 'bride.pesel',
    section: 'bride',
    labelPl: 'PESEL Panny Młodej',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 55,
  },
  {
    key: 'groom.pesel',
    section: 'groom',
    labelPl: 'PESEL Pana Młodego',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 155,
  },
  {
    key: 'wedding.schedule',
    section: 'wedding',
    labelPl: 'Harmonogram',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 240,
  },
  {
    key: 'studio.owner',
    section: 'studio',
    labelPl: 'Właściciel',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 612,
  },
  {
    key: 'studio.vat',
    section: 'studio',
    labelPl: 'VAT',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 635,
  },
  {
    key: 'studio.signature',
    section: 'studio',
    labelPl: 'Podpis',
    valueType: 'string',
    dataSource: 'studio',
    isSystem: true,
    sortOrder: 695,
  },
  {
    key: 'additional.notes',
    section: 'additional',
    labelPl: 'Uwagi',
    valueType: 'string',
    dataSource: 'wedding',
    isSystem: true,
    sortOrder: 730,
  },
]

const byKey = new Map(DOCUMENT_VARIABLES.map((v) => [v.key, v]))

export function getVariableDef(key: string): DocumentVariableDef | undefined {
  return byKey.get(key)
}

export function variablesForSection(
  section: DocumentVariableSection,
): DocumentVariableDef[] {
  return DOCUMENT_VARIABLES.filter((v) => v.section === section)
}

export function isKnownVariableKey(key: string): boolean {
  return byKey.has(key)
}

/** Polish UI label — Variable Registry is the only source. */
export function registryDisplayLabel(key: string): string {
  return byKey.get(key)?.labelPl ?? 'Informacja'
}
