import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const root = `${process.cwd()}/src/features/contract-generation-spike`
const adapter = await readFile(`${root}/contractGenerationInput.ts`, 'utf8')
const generator = await readFile(`${root}/generator.ts`, 'utf8')
const harness = await readFile(`${root}/multi-template-acceptance/harness.ts`, 'utf8')

assert.doesNotMatch(adapter, /JSZip|readSource|sourceDocx|parse.*(?:docx|document)|inventory/i)
assert.doesNotMatch(adapter, /new RegExp|\.match\(|\.matchAll\(/, 'adapter does not inspect text with regex or prose parsers')
assert.doesNotMatch(adapter, /supabase|\.from\(|\.insert\(|\.update\(|\.delete\(/i, 'adapter has no database client or writes')
assert.doesNotMatch(adapter, /contractNumber|agreementNumber|payment.*prose|questionnaire.*label/i, 'adapter has no contract ontology or UI-label interpretation')
assert.doesNotMatch(adapter, /party.*name.*includes|address.*includes|includes.*address/i, 'adapter does not infer identity/address ownership from values')
assert.match(adapter, /form_answers\.answer_json\.fields\.\$\{key\}.*owner/s, 'ownership comes from the submitted semantic key path')
assert.match(adapter, /contractAddress\?: ContractGenerationFact<string>/, 'contract address has a top-level normalized authority fact')
assert.match(adapter, /contractAddressFact[\s\S]*semanticType: 'contract_address'/, 'contract address retains explicit semantic provenance')
assert.doesNotMatch(adapter, /owner: 'partner1',[\s\S]{0,80}semanticType: 'contract_address'/, 'contract-level address has no participant owner')
assert.doesNotMatch(generator, /buildContractGenerationInput/)
assert.match(generator, /applyOptionBGenerationResponse/, 'generator applies the strict block-edit response through the existing editor')
assert.match(generator, /validateOptionBInput\(input: ContractGenerationInput\)/, 'generation retains normalized-input and arithmetic validation')
assert.match(harness, /buildContractGenerationInput/, 'harness normalizes both current and compatibility fixture inputs through the adapter')
assert.doesNotMatch(harness, /\bcontractNumber\b|\bagreementNumber\b|\bpesel\b/i, 'harness does not interpret human identifiers or PESELs')
assert.doesNotMatch(harness, /parse.*(?:payment|address|questionnaire).*prose|questionnaire.*label.*(?:nlp|interpret)/i, 'harness does not add semantic parsers')
assert.doesNotMatch(harness, /partyName.*(?:includes|match)|address.*(?:includes|match).*name/i, 'harness does not infer party ownership from values')
assert.match(harness, /generate\(args: \{ instructions: string; sourceBlocks:/, 'one generation provider call receives instructions, source blocks, and normalized authority')
assert.match(harness, /provider\.generate\(/, 'the active harness invokes the single generation provider method')
assert.match(harness, /authorityContext: normalizedInput/, 'the normalized adapter result is passed directly to generation')
assert.match(harness, /productRules: GENERIC_CONTRACT_PRODUCT_RULES/, 'the active generation request includes generic product rules')
assert.match(harness, /provider\.review\(/, 'the independent reviewer runs after successful mechanical validation')
assert.match(harness, /providerCalls\.reviewer = 1/, 'READY candidates reach one reviewer call')
assert.match(harness, /if \(generatedResult\.status === 'FAILED'\)[\s\S]*?return result[\s\S]*?providerCalls\.reviewer = 1/, 'mechanical failure returns before reviewer invocation')
assert.doesNotMatch(harness, /provider\.(?:inventory|plan)\(/, 'the active harness has no separate inventory or planner stage')
assert.match(harness, /REVIEW_INSTRUCTIONS/, 'reviewer receives the independent review rubric')
console.log('PASS ContractGenerationInput architecture boundary acceptance')
