import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const root = `${process.cwd()}/src/features/contract-generation-spike`
const adapter = await readFile(`${root}/contractGenerationInput.ts`, 'utf8')
const generator = await readFile(`${root}/generator.ts`, 'utf8')
const harness = await readFile(`${root}/multi-template-acceptance/harness.ts`, 'utf8')
const providerBoundary = await readFile(`${root}/plannerProviderBoundary.ts`, 'utf8')

assert.doesNotMatch(adapter, /JSZip|readSource|sourceDocx|parse.*(?:docx|document)|inventory/i)
assert.doesNotMatch(adapter, /new RegExp|\.match\(|\.matchAll\(/, 'adapter does not inspect text with regex or prose parsers')
assert.doesNotMatch(adapter, /supabase|\.from\(|\.insert\(|\.update\(|\.delete\(/i, 'adapter has no database client or writes')
assert.doesNotMatch(adapter, /contractNumber|agreementNumber|payment.*prose|questionnaire.*label/i, 'adapter has no contract ontology or UI-label interpretation')
assert.doesNotMatch(adapter, /party.*name.*includes|address.*includes|includes.*address/i, 'adapter does not infer identity/address ownership from values')
assert.match(adapter, /form_answers\.answer_json\.fields\.\$\{key\}.*owner/s, 'ownership comes from the submitted semantic key path')
assert.match(adapter, /genericContractAddress[\s\S]*unownedFacts/, 'generic correspondence address stays in the unowned fact collection')
assert.doesNotMatch(generator, /buildContractGenerationInput/)
assert.match(generator, /plan\(authorityContext: ContractGenerationInput/, 'core planner interface consumes normalized authority directly')
assert.match(generator, /ai\.plan\(authorityContext, inventory\)/, 'generation passes normalized authority to the planner')
assert.match(generator, /authorityContext: ContractGenerationInput/, 'independent review receives normalized authority directly')
assert.doesNotMatch(generator, /plan\(input: GenerationInput/, 'legacy input is not the planner parameter')
assert.doesNotMatch(generator, /review\(args: \{[^}]*input: GenerationInput/, 'legacy input is not the reviewer parameter')
assert.match(harness, /buildContractGenerationInput/, 'harness normalizes both current and compatibility fixture inputs through the adapter')
assert.doesNotMatch(harness, /\bcontractNumber\b|\bagreementNumber\b|\bpesel\b/i, 'harness does not interpret human identifiers or PESELs')
assert.doesNotMatch(harness, /parse.*(?:payment|address|questionnaire).*prose|questionnaire.*label.*(?:nlp|interpret)/i, 'harness does not add semantic parsers')
assert.doesNotMatch(harness, /partyName.*(?:includes|match)|address.*(?:includes|match).*name/i, 'harness does not infer party ownership from values')
assert.match(harness, /transform\(args: \{ authorityContextDescription: string; authorityContext: ContractGenerationInput/, 'planner provider boundary consumes the normalized authority input')
assert.match(harness, /authorityContext: normalizedInput/, 'the normalized adapter result is passed directly to the planner provider')
assert.doesNotMatch(harness, /transform\(args: \{ input: GenerationInput/, 'legacy GenerationInput is not sent to the planner provider')
assert.doesNotMatch(harness, /review\(args: \{[^}]*input: GenerationInput/, 'legacy GenerationInput is not sent to the reviewer provider')
assert.match(providerBoundary, /JSON\.stringify\(createPlannerAuthorityContextPayload\(input\)\)/, 'provider transport serializes a transparent envelope around the normalized object')
const providerBoundaryCode = providerBoundary.replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, '')
assert.doesNotMatch(providerBoundaryCode, /PESEL|agreement\.identifier|contractNumber|clients\.address|parseFlexible|infer|classif|heuristic/i)
console.log('PASS ContractGenerationInput architecture boundary acceptance')
